name: wordle6
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: 1.5.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
